### ISSUE TITLE
auth not working

### ISSUE THREAD

**Issue by ironytr** [yopinoji/nuxt3-fastapi-mysql#8]
Hello, when i refresh the page its redirecting to signin page. also i dont see any token header when request is happen. How can i add bearer token to header? (im using inertiajs vue2 doing stuffs good dont know anything about ssr techs :) )  i want to use this for my basic learning project. Any help appreicated. Ty.

**Comment by qlawmarq** [comment]
Hi, @ironytr.
Sorry, I didn't realize your comment sooner.

> when i refresh the page its redirecting to signin page

I added a checking auth script when the app is reloaded.
Please check [this PR](https://github.com/masaiborg/nuxt3-tailwind-sample-auth-app/pull/9/files) for more details.


> How can i add bearer token to header?

In this application, Axios is used as a library for HTTP communication.
https://axios-http.com/docs/interceptors

Please check [following](https://github.com/masaiborg/nuxt3-tailwind-sample-auth-app/blob/main/pages/profile/edit.vue#L103) to see how to add bearer token to header:
```ts
      apiClient.interceptors.request.use(function (config) {
          const token = auth.authState.value?.access_token
          config.headers.Authorization =  `Bearer ${token}`;
          return config;
      });
      const res = await ApiService.updateUser(values)
```

I hope this will help you :)
